/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentBankType } from './agentBankType';
import { AgentRemittance } from './agentRemittance';

export interface AgentCardRequestRemittance { 
    Id?: number;
    CardId?: number;
    DateRequested?: Date;
    TransactionNo?: string;
    Type?: AgentBankType;
    Destination?: number;
    CardReferenceNo?: string;
    Source?: number;
    DateRemitted?: Date;
    Amount?: number;
    Status?: AgentRemittance;
    RemittanceId?: string;
    ApprovedBy?: number;
    Remarks?: string;
}