/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentClientCommission } from './agentClientCommission';
import { AgentStatus } from './agentStatus';
import { AgentTypeEnum } from './agentTypeEnum';
import { Client } from './client';
import { User } from './user';

export interface Agent { 
    AgentId?: number;
    UserId?: number;
    Username?: string;
    Email?: string;
    ParentAgentId?: number;
    AgentLevel?: number;
    AgentName?: string;
    AgentType?: AgentTypeEnum;
    Status?: AgentStatus;
    CreatedAt?: Date;
    UpdatedAt?: Date;
    WalletBalance?: number;
    RemittanceBalance?: number;
    TotalCiCommission?: number;
    TotalCoCommission?: number;
    User?: User;
    ParentAgent?: Agent;
    SubAgents?: Array<Agent>;
    Brands?: Array<Client>;
    AgentClientCommissions?: Array<AgentClientCommission>;
}