/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Agent } from './agent';
import { Client } from './client';
import { Commission } from './commission';
import { StatusEnum } from './statusEnum';

export interface AgentClientCommission { 
    CommissionId?: number;
    AgentId?: number;
    Agent?: Agent;
    ClientId?: number;
    Client?: Client;
    CiCommissionRate?: number;
    CoCommissionRate?: number;
    Status?: StatusEnum;
    Commissions?: Array<Commission>;
}