/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentBalanceTransfer } from './agentBalanceTransfer';
import { AgentShortened } from './agentShortened';
import { ClientShortened } from './clientShortened';
import { UserAdminShortened } from './userAdminShortened';

export interface AgentRequestForBalanceTransferDTO { 
    Id?: number;
    RequestID?: string;
    Status?: AgentBalanceTransfer;
    StatusDescription?: string;
    TotalAmount?: number;
    TimeStamp?: Date;
    Remarks?: string;
    Client?: ClientShortened;
    Requestee?: AgentShortened;
    RequestedByAdmin?: UserAdminShortened;
}