/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AgentIdType = 1 | 2 | 3 | 4;

export const AgentIdType = {
    NUMBER_1: 1 as AgentIdType,
    NUMBER_2: 2 as AgentIdType,
    NUMBER_3: 3 as AgentIdType,
    NUMBER_4: 4 as AgentIdType
};