/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentBankType } from './agentBankType';
import { ShortenedAgent } from './shortenedAgent';
import { ShortenedReceipt } from './shortenedReceipt';
import { ShortenedUser } from './shortenedUser';

export interface AgentApprovedRemittanceRequest { 
    Id?: number;
    TimeStamp?: Date;
    RemittanceId?: string;
    Agent?: ShortenedAgent;
    TotalAmount?: number;
    WithdrawalCount?: number;
    DateRemitted?: Date;
    ModeOfPayment?: AgentBankType;
    Source?: number;
    Receipts?: Array<ShortenedReceipt>;
    ApprovedBy?: ShortenedUser;
    Remarks?: string;
}