/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentBankType } from './agentBankType';
import { AgentCard } from './agentCard';
import { AgentRemittance } from './agentRemittance';
import { User } from './user';

export interface AgentCardTransaction { 
    Id?: number;
    CardId: number;
    AgentCards?: AgentCard;
    DateRequested?: Date;
    TransactionNo: string;
    Type: AgentBankType;
    Destination?: string;
    CardReferenceNo?: string;
    Source?: number;
    DateRemitted?: Date;
    Amount?: number;
    WithdrawalFee?: number;
    TotalAmount?: number;
    Status?: AgentRemittance;
    RemittanceId?: string;
    RemittanceReferenceNo?: string;
    WithdrawalCount?: number;
    ApprovedBy?: number;
    User?: User;
    Remarks?: string;
}