/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AgentTypeEnum = 1 | 2 | 3 | 4;

export const AgentTypeEnum = {
    NUMBER_1: 1 as AgentTypeEnum,
    NUMBER_2: 2 as AgentTypeEnum,
    NUMBER_3: 3 as AgentTypeEnum,
    NUMBER_4: 4 as AgentTypeEnum
};