/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentReportTransactionLogList } from './agentReportTransactionLogList';
import { LeftSideSummaryReport } from './leftSideSummaryReport';
import { Pagination } from './pagination';
import { RightSideSummaryReport } from './rightSideSummaryReport';

export interface AgentReportTransactionLog { 
    Pagination?: Pagination;
    TotalCommissions?: RightSideSummaryReport;
    WalletBalance?: LeftSideSummaryReport;
    Transactions?: Array<AgentReportTransactionLogList>;
}