/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentStatus } from './agentStatus';
import { AgentTypeEnum } from './agentTypeEnum';

export interface AgentsComm { 
    AgentId?: number;
    AgentName?: string;
    AgentType?: AgentTypeEnum;
    CiCommissionRate?: number;
    CoCommissionRate?: number;
    Username?: string;
    Email?: string;
    DateAdded?: Date;
    Status?: AgentStatus;
    ParentAgent?: AgentsComm;
    SubAgents?: Array<AgentsComm>;
}