/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentBalanceTransfer } from './agentBalanceTransfer';
import { PChannels } from './pChannels';

export interface ApproveResponseDTO { 
    Id?: number;
    RequestID?: string;
    ClientId?: number;
    ClientName?: string;
    RequesterId?: number;
    RequesterName?: string;
    Status?: AgentBalanceTransfer;
    StatusDescription?: string;
    TotalAmount?: number;
    TimeStamp?: Date;
    ApprovedBy?: number;
    ApproverName?: string;
    Remarks?: string;
    DateCompleted?: Date;
    PaymentChannels?: Array<PChannels>;
}