/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BalanceTransferBreakdownDestinationDTO { 
    Id?: number;
    Amount?: number;
    DestinationMerchantId?: number;
    BalanceTransferId?: number;
    CreatedDate?: Date;
    CompletedDate?: Date;
    VendorId?: number,
    VendorName?: string,
    TransactionNumber?: string
}