/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CashInStatusEnum = 1 | 2 | 3 | 4;

export const CashInStatusEnum = {
    NUMBER_1: 1 as CashInStatusEnum,
    NUMBER_2: 2 as CashInStatusEnum,
    NUMBER_3: 3 as CashInStatusEnum,
    NUMBER_4: 4 as CashInStatusEnum
};