/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Provider } from './provider';
import { StatusEnum } from './statusEnum';

export interface Client { 
    Id?: number;
    Name: string;
    TransactionCount?: number;
    RemittanceWalletBalance?: number;
    TotalCashIn?: number;
    TotalCashOut?: number;
    Balance?: number;
    Status?: StatusEnum;
    CreatedDate?: Date;
    LastUpdatedDate?: Date;
    ProviderId?: number;
    CallbackUrl?: string;
    RedirectUrl?: string;
}