/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ClientAggregatesDTO { 
    ClientId?: number;
    TotalClients?: number;
    AvailableBalance?: number;
    TotalCashIn?: number;
    TotalCashOut?: number;
    TotalWithdrawals?: number;
}