/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ClientWithdrawalsHistoryDTO { 
    dateRequested?: Date;
    dateReleased?: Date;
    clientName?: string;
    amount?: number;
    wFeeTotal?: number;
    netAmount?: number;
    referenceNo?: string;
    released?: string;
    receipt?: string;
    status?: string;
}