/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentClientCommission } from './agentClientCommission';

export interface Commission { 
    CommissionId?: number;
    AgentClientCommissionId?: number;
    AgentClientCommission?: AgentClientCommission;
    CoCommissionAmount?: number;
    CiCommissionAmount?: number;
    AgentWalletBalance?: number;
    AgentRemittanceBalance?: number;
}