/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClientShortenedDTO } from './clientShortenedDTO';
import { FeeDTO } from './feeDTO';
import { MerchantVendorDTO } from './merchantVendorDTO';
import { PaymentChannelDTO } from './paymentChannelDTO';
import { StatusEnum } from './statusEnum';
import { TransactionTypeEnum } from './transactionTypeEnum';

export interface ConfigureFeeDTO { 
    Id?: number;
    TransactionType?: TransactionTypeEnum;
    FeeOnTopPercent?: number;
    FeeOnTopFixed?: number;
    FeeAtCostPercent?: number;
    FeeAtCostFixed?: number;
    LastUpdatedDate?: Date;
    Status?: StatusEnum;
}
export interface MerchantDTO {
    Id?: number;
    PublicIdCashIn?: number;
    PublicIdCashOut?: number;
    Name?: string;
    TotalCashIn?: number;
    TotalCashOut?: number;
    TotalTransferredToRemittanceWallet?: number;
    Balance?: number;
    TopUpBalance?: number;
    Status?: StatusEnum;
    CreatedDate?: Date;
    LastUpdatedDate?: Date;
    CashInFee?: FeeDTO;
    CashOutFee?: FeeDTO;
    PaymentChannel?: PaymentChannelDTO;
    Vendor?: MerchantVendorDTO;
    Client?: ClientShortenedDTO;
    ConfigureStatus?: ConfigureFeeDTO;

}
