/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WithdrawalTypeEnum } from './withdrawalTypeEnum';

export interface CreateCardWithdrawalRequestDTO { 
    IdCardDestination?: number;
    ClientId?: number;
    RequesterUserId?: number;
    RequesterName?: string;
    Method?: WithdrawalTypeEnum;
    FeeOnTop?: number;
    FeeOnTopPercent?:number;
    FeeOnTopFixed?:number;
    FeeAtCost?: number;
    FeeAtCostPercent?: number;
    FeeAtCostFixed?:number;
    WithdrawalFee?: number;
    Amount?: number;
    NetAmount?: number;
}