/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CardTypeEnum } from './cardTypeEnum';

export interface CreateCardRequestDTO { 
    ClientId?: number;
    CardType?: CardTypeEnum;
    BankName?: string;
    AccountNumber?: string;
    AccountName?: string;
    NickName?: string;
    BinanceWalletAddress?: string;
    readonly isMainCard?: boolean;
}