/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentBalanceTransfer } from './agentBalanceTransfer';

export interface DeclineResponseDTO { 
    id?: number;
    requestID?: string;
    clientId?: number;
    clientName?: string;
    requesterId?: number;
    requesterName?: string;
    status?: AgentBalanceTransfer;
    statusDescription?: string;
    totalAmount?: number;
    timeStamp?: Date;
    approvedBy?: number;
    approverName?: string;
    remarks?: string;
    dateCompleted?: Date;
}