/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DigipayManualCallbackDTO { 
    id?: number;
    transactionNumber?: string;
    orderNumber?: string;
    merchantId?: number;
    amount?: number;
    fees?: number;
    total?: number;
    createdDate?: Date;
    completedDate?: Date;
    vendorInitiatedTime?: string;
    vendorResponseTime?: string;
}