/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionTypeEnum } from './transactionTypeEnum';

export interface FeeDTO { 
    Id?: number;
    Name?: string;
    TransactionType?: TransactionTypeEnum;
    FeeOnTopPercent?: number;
    FeeOnTopFixed?: number;
    FeeAtCostPercent?: number;
    FeeAtCostFixed?: number;
    CreatedDate?: Date;
    LastUpdatedDate?: Date;
    
}