/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IncomeReportData { 
    Date?: Date;
    DayOfWeek?: string;
    CICount?: number;
    CIGross?: number;
    CIFeeOnTop?: number;
    CIFeeAtCost?: number;
    readonly CINet?: number;
    COCount?: number;
    COGross?: number;
    COFeeOnTop?: number;
    COFeeAtCost?: number;
    readonly CONet?: number;
    WCount?: number;
    WGross?: number;
    WFeeOnTop?: number;
    WFeeAtCost?: number;
    readonly WNet?: number;
    readonly TotalGross?: number;
    readonly TotalFee_OT?: number;
    readonly TotalFeeAC?: number;
    readonly TotalNet?: number;
    readonly TotalIncome?: number;
}