/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusEnum } from './statusEnum';
import { User } from './user';
import { VerificationEnum } from './verificationEnum';

export interface IPWhitelist { 
    Id?: number;
    WhitelistedIp: string;
    LastLogin?: Date;
    Status?: StatusEnum;
    Verification?: VerificationEnum;
    UserId: number;
    User?: User;
}