/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IPWhitelistDTO { 
    Id?: number;
    Username?: string;
    ClientName?: string;
    Role?: string;
    Ip?: string;
    LastLogin?: Date;
    Verification?: string;
    Status?: string;
}