/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MerchantFeeActionEnum = 0 | 1 | 2 | 3;

export const MerchantFeeActionEnum = {
    NUMBER_0: 0 as MerchantFeeActionEnum,
    NUMBER_1: 1 as MerchantFeeActionEnum,
    NUMBER_2: 2 as MerchantFeeActionEnum,
    NUMBER_3: 3 as MerchantFeeActionEnum
};