/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeeUpdateDTO } from './feeUpdateDTO';
import { StatusEnum } from './statusEnum';

export interface MerchantUpdateDTO { 
    id?: number;
    name?: string;
    status?: StatusEnum;
    lastUpdatedDate?: Date;
    vendorId?: number;
    clientId?: number;
    fee: FeeUpdateDTO;
}