/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MerchantControllerEnum = 0 | 1 | 2 | 3;

export const MerchantControllerEnum = {
    NUMBER_0: 0 as MerchantControllerEnum,
    NUMBER_1: 1 as MerchantControllerEnum,
    NUMBER_2: 2 as MerchantControllerEnum,
    NUMBER_3: 3 as MerchantControllerEnum
};