/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MerchantFeeActionEnum } from './merchantFeeActionEnum';
import { MerchantFeeTypeEnum } from './merchantFeeTypeEnum';

export interface MerchantFeesDTO { 
    id?: number;
    name?: string;
    merchantId?: number;
    type?: MerchantFeeTypeEnum;
    feeValue?: number;
    action?: MerchantFeeActionEnum;
    createdDate?: Date;
    lastUpdatedDate?: Date;
}