/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MerchantProviderEnum = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const MerchantProviderEnum = {
    NUMBER_1: 1 as MerchantProviderEnum,
    NUMBER_2: 2 as MerchantProviderEnum,
    NUMBER_3: 3 as MerchantProviderEnum,
    NUMBER_4: 4 as MerchantProviderEnum,
    NUMBER_5: 5 as MerchantProviderEnum,
    NUMBER_6: 6 as MerchantProviderEnum,
    NUMBER_7: 7 as MerchantProviderEnum
};