/**
 * DynastyGateway API
 * API Connections to DPay
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProfitSummaryData } from "../api/profitSummaryData";
import { ProfitSummaryDTOGrandTotals } from "./profitSummaryDTOGrandTotals";


export interface ProfitSummaryDTO { 
    GrandTotals?: ProfitSummaryDTOGrandTotals;
    Reports?: Array<ProfitSummaryData>;
    TotalRecordCount?: number;
    Pagesize?: number;
    PageNumber?: number;
}