/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentBankType } from './agentBankType';
import { AgentRemittance } from './agentRemittance';
import { ShortenedRemUser } from './shortenedRemUser';

export interface RemittnaceDeclineDTO { 
    Id?: number;
    TimeStamp?: Date;
    RemittanceId?: string;
    TotalAmount?: number;
    DateRemitted?: Date;
    ModeOfPayment?: AgentBankType;
    ApprovedBy?: ShortenedRemUser;
    Remarks?: string;
    Status?: AgentRemittance;
    StatusDescription?: string;
}