/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SuccessRate { 
    Timestamp?: Date;
    ClientId?: number;
    ClientName?: string;
    TransactionCountCI?: number;
    TransactionCountCO?: number;
    TransactionCountCICO?: number;
    TotalSuccessCI?: number;
    TotalSuccessCO?: number;
    TotalSuccessCICO?: number;
    SuccessRateCI?: number;
    SuccessRateCO?: number;
    SuccessRateCICO?: number;
    TotalPendingCI?: number;
    TotalPendingCO?: number;
    TotalPendingCICO?: number;
    TotalRejectedCI?: number;
    TotalRejectedCO?: number;
    TotalRejectedCICO?: number;
    TotalClosedCI?: number;
    TotalClosedCO?: number;
    TotalClosedCICO?: number;
    TotalCancelledCI?: number;
    TotalCancelledCO?: number;
    TotalCancelledCICO?: number;
}