/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SummaryReportData } from './summaryReportData';

export interface SummaryReport { 
    TotalRecordCount?: number;
    ClientId?: number;
    TotalGrossAmount?: number;
    TotalAtCostFee?: number;
    TotalOnTopFee?: number;
    TotalNetAmount?: number;
    TotalGcash?: number;
    TotalMaya?: number;
    TotalgrabPay?: number;
    TotalInstaPay?: number;
    TotalQRPH?: number;
    PageSize?: number;
    PageNumber?: number;
    Data?: Array<SummaryReportData>;
}