/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CashInOutStatusEnum } from './cashInOutStatusEnum';

export interface SummaryReportData { 
    Timestamp?: Date;
    TransactionNo?: number;
    InternalTransactionNumber?: string;
    UserID?: string;
    ClientName?: string;
    Type?: string;
    MerchantName?: string;
    PMethod?: string;
    GrossAmount?: number;
    FixFee?: number;
    FeesPercent?: number;
    NetAmount?: number;
    Status?: CashInOutStatusEnum;
    StatusDescription?: string;
    TopUpBalance?: number;
    VendorResponseTime?: string;
}