/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TopUpSummaryData } from './topUpSummaryData';
import { WalletData } from './walletData';

export interface TopUpSummaryReport { 
    totalRecordCount?: number;
    pageNumber?: number;
    pageSize?: number;
    clientId?: number;
    totalCOFundsAvailable?: number;
    totalTopUps?: number;
    topUpData?: Array<TopUpSummaryData>;
    myWalletData?: Array<WalletData>;
}