/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TopUpStatusEnum } from './topUpStatusEnum';

export interface TopUpSummaryData { 
    Id?: number;
    Amount?: number;
    InternalTransactionNumber?: string;
    CompletedDate?: Date;
    CreatedDate?: Date;
    ReferenceNumber?: string;
    Type?: string;
    ApproverName?: string;
    ClientId?: number;
    ClientName?: string;
    Requestee?: string;
    RequesteeName?: string;
    Status?: TopUpStatusEnum;
    StatusDescription?: string;
    Remarks?: string;
    Receipt?: string;
}