/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CashInOutStatusEnum } from './cashInOutStatusEnum';
import { ClientDTO } from './clientDTO';
import { TransactionTypeEnum } from './transactionTypeEnum';

export interface TransactionLogDTO { 
    Id?: number;
    ReferenceId?: number;
    Type?: TransactionTypeEnum;
    Amount?: number;
    Fee?: number;
    Total?: number;
    Description?: string;
    RunningBalanceBefore?: number;
    RunningBalanceAfter?: number;
    Status?: CashInOutStatusEnum;
    CreatedDate?: Date;
    CompletedDate?: Date;
    ClientId?: number;
    ReferenceUserId?: string;
    Client?: ClientDTO;
}