/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TransactionSummaryDTO { 
    clientId?: number;
    todayIncome?: number;
    todayNetIncome?: number;
    yesterdayIncome?: number;
    yesterdayNetIncome?: number;
    thisWeekIncome?: number;
    thisWeekNetIncome?: number;
    thisMonthIncome?: number;
    thisMonthNetIncome?: number;
    totalIncome?: number;
    totalNetIncome?: number;
    totalCashIn?: number;
    totalCashOut?: number;
    totalWithdrawals?: number;
}