/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionTypeEnum } from './transactionTypeEnum';

export interface UpdateFeeRequestDTO { 
    id?: number;
    name?: string;
    transactionType?: TransactionTypeEnum;
    feeOnTopPercent?: number;
    feeOnTopFixed?: number;
    feeAtCostPercent?: number;
    feeAtCostFixed?: number;
}