/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Client } from './client';
import { IPWhitelist } from './iPWhitelist';
import { OTP } from './oTP';
import { Role } from './role';
import { StatusEnum } from './statusEnum';

export interface User { 
    Id?: number;
    Username: string;
    PasswordHashed: string;
    Name: string;
    Email: string;
    Status?: StatusEnum;
    Token?: string;
    LastLoginIP?: string;
    LastLoginDate?: Date;
    CreatedDate?: Date;
    LastUpdatedDate?: Date;
    LastUpdatedBy?: string;
    OTPIsVerified?: boolean;
    OTPIsEnabled?: boolean;
    PasswordDidChanged?: boolean;
    PasswordLastUpdated?: Date;
    RefreshToken?: string;
    RefreshTokenExpiryTime?: Date;
    PasswordResetToken?: string;
    PasswordResetTokenExpiryTime?: Date;
    Otp?: OTP;
    ClientId: number;
    Client?: Client;
    RoleId: number;
    Role?: Role;
    WhitelistedIPs?: Array<IPWhitelist>;
}