/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RemittanceWalletRequestTransferFundsSourceDTO } from './remittanceWalletRequestTransferFundsSourceDTO';
import { TopUpStatusEnum } from './topUpStatusEnum';

export interface UserUpdateTransferFundsRequestDTO { 
    TransactionNumber?: string;
    Status?: TopUpStatusEnum;
    Sources?: Array<RemittanceWalletRequestTransferFundsSourceDTO>;
    Remarks?: string;
}