/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BalanceTransferBreakdownDestinationDTO } from './balanceTransferBreakdownDestinationDTO';
import { BalanceTransferBreakdownSourceDTO } from './balanceTransferBreakdownSourceDTO';
import { TopUpStatusEnum } from './topUpStatusEnum';

export interface UserBalanceTransferDTO { 
    Id?: number;
    SourceMerchants?: Array<BalanceTransferBreakdownSourceDTO>;
    DestinationMerchants?: Array<BalanceTransferBreakdownDestinationDTO>;
    TransactionNumber?: string;
    Requestee?: string;
    Status?: TopUpStatusEnum;
    StatusDescription?: string;
    Amount?: number;
    Fees?: number;
    Total?: number;
    CreatedDate?: Date;
    CompletedDate?: Date;
    ApprovedBy?: string;
    Remarks?: string;
}