/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TopUpStatusEnum } from './topUpStatusEnum';
import { BalanceTransferBreakdownDestinationDTO } from './balanceTransferBreakdownDestinationDTO';
import { BalanceTransferBreakdownSourceDTO } from './balanceTransferBreakdownSourceDTO';

export interface UserUpdateBalanceTransferRequestDTO { 
    TransactionNumber?: string;
    Status?: TopUpStatusEnum;
    Destinations?: Array<BalanceTransferBreakdownDestinationDTO>;
    Sources?: Array<BalanceTransferBreakdownSourceDTO>;
    Remarks?:string;
}