/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UserRoleEnum = 1 | 2 | 3 | 4;

export const UserRoleEnum = {
    NUMBER_1: 1 as UserRoleEnum,
    NUMBER_2: 2 as UserRoleEnum,
    NUMBER_3: 3 as UserRoleEnum,
    NUMBER_4: 4 as UserRoleEnum
};