/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TopUpStatusEnum } from './topUpStatusEnum';

export interface UserTopUpDTO { 
    id?: number;
    clientId?: number;
    transactionNumber?: string;
    requestee?: string;
    status?: TopUpStatusEnum;
    statusDescription?: string;
    amount?: number;
    fees?: number;
    total?: number;
    createdDate?: Date;
    completedDate?: Date;
    dateOfDeposit?: Date;
    approvedBy?: string;
    remarks?: string;
}