/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ValidIDEnum = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export const ValidIDEnum = {
    NUMBER_0: 0 as ValidIDEnum,
    NUMBER_1: 1 as ValidIDEnum,
    NUMBER_2: 2 as ValidIDEnum,
    NUMBER_3: 3 as ValidIDEnum,
    NUMBER_4: 4 as ValidIDEnum,
    NUMBER_5: 5 as ValidIDEnum,
    NUMBER_6: 6 as ValidIDEnum,
    NUMBER_7: 7 as ValidIDEnum,
    NUMBER_8: 8 as ValidIDEnum,
    NUMBER_9: 9 as ValidIDEnum
};