/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WithdrawalsReportData } from './withdrawalsReportData';

export interface WithdrawalsReport { 
    TotalRecordCount?: number;
    ClientId?: number;
    TotalGrossAmount?: number;
    TotalAtCostFee?: number;
    TotalOnTopFee?: number;
    TotalNetAmount?: number;
    TotalBank?: number;
    TotalUsdt?: number;
    TotalCashPickup?: number;
    TotalEwallet?: number;
    PageSize?: number;
    PageNumber?: number;
    Data?: Array<WithdrawalsReportData>;
}