/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WithdrawalsReportData {
    
    DateRequested?: Date;
    RemittanceId?: string;
    UserID?: string;
    Requestee?: string;
    ClientName?: string;
    Type?: string;
    Method?: string;
    DateRemitted?: string;
    ReferenceNumber?: string;
    RequestedAmount?: number;
    FeeOT?: number;
    FeeOTPercent?: number;
    FeeOTFixed?: number;
    FeeAC?: number;
    FeeACPercent?: number;
    FeeACFixed?: number;
    Fee?: number;
    NetAmount?: number;
    Status?: string;
    CardIdFundSourceMother?: number;
    ApproverName?: string;
    CardBankName?: string;
    CardAccountName?: string;
    CardAccountNumber?: string;
    TransactionCount?: number;
    MotherCardBankName?: string;
    MotherCardAccountName?: string;
    MotherCardAccountNumber?: string;
}