/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { ActivityLogDTO } from '../model/activityLogDTO';
import { ProblemDetails } from '../model/problemDetails';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { environment } from 'src/environments/environment';
import { ActivityLogListDTO } from '../model/activityLogListDTO';


@Injectable()
export class ActivityLogsService {

    protected basePath = environment.basePath;
    public token = sessionStorage.getItem("token") || '';
    public defaultHeaders = new HttpHeaders({
        'X-API-KEY': environment.APIkey,
        'Authorization': this.token ? `Bearer ${this.token}` : '',
    });
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get the activity logs of users.
     * 
     * @param searchKeyword 
     * @param startDate 
     * @param endDate 
     * @param userName 
     * @param clientName 
     * @param clientId 
     * @param action 
     * @param role 
     * @param page 
     * @param limit 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiActivityLogsGetActivityLogsGet(searchKeyword?: string, startDate?: Date, endDate?: Date, userName?: string, clientName?: string, clientId?: number, action?: string, role?: string, page?: number, limit?: number, observe?: 'body', reportProgress?: boolean): Observable<ActivityLogListDTO>;
    public apiActivityLogsGetActivityLogsGet(searchKeyword?: string, startDate?: Date, endDate?: Date, userName?: string, clientName?: string, clientId?: number, action?: string, role?: string, page?: number, limit?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ActivityLogListDTO>>;
    public apiActivityLogsGetActivityLogsGet(searchKeyword?: string, startDate?: Date, endDate?: Date, userName?: string, clientName?: string, clientId?: number, action?: string, role?: string, page?: number, limit?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ActivityLogListDTO>>;
    public apiActivityLogsGetActivityLogsGet(searchKeyword?: string, startDate?: Date, endDate?: Date, userName?: string, clientName?: string, clientId?: number, action?: string, role?: string, page?: number, limit?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {











        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (searchKeyword !== undefined && searchKeyword !== null) {
            queryParameters = queryParameters.set('SearchKeyword', <any>searchKeyword);
        }
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('EndDate', <any>endDate.toISOString());
        }
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('UserName', <any>userName);
        }
        if (clientName !== undefined && clientName !== null) {
            queryParameters = queryParameters.set('ClientName', <any>clientName);
        }
        if (clientId !== undefined && clientId !== null) {
            queryParameters = queryParameters.set('ClientId', <any>clientId);
        }
        if (action !== undefined && action !== null) {
            queryParameters = queryParameters.set('Action', <any>action);
        }
        if (role !== undefined && role !== null) {
            queryParameters = queryParameters.set('Role', <any>role);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('Page', <any>page);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('Limit', <any>limit);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // authentication (apiKey) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["X-API-KEY"]) {
            headers = headers.set('X-API-KEY', this.configuration.apiKeys["X-API-KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ActivityLogListDTO>('get',`${this.basePath}/api/ActivityLogs/GetActivityLogs`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
