/**
 * Dynasty Cash In Gateway
 * Dynasty Cash In API list
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { OtpDTO } from '../model/otpDTO';
import { ProblemDetails } from '../model/problemDetails';
import { UserOtpRequestDTO } from '../model/userOtpRequestDTO';
import { UserOtpValidateRequestDTO } from '../model/userOtpValidateRequestDTO';
import { UserOtpValidateResultDTO } from '../model/userOtpValidateResultDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { environment } from 'src/environments/environment';


@Injectable()
export class OtpsService {

    protected basePath = environment.basePath;
    public token = sessionStorage.getItem("token") || ''; 
    public defaultHeaders = new HttpHeaders({
        'X-API-KEY':environment.APIkey,
        'Authorization': this.token ? `Bearer ${this.token}` : '',
     });
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiOtpsGenerateOtpPost(body?: UserOtpRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<OtpDTO>;
    public apiOtpsGenerateOtpPost(body?: UserOtpRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OtpDTO>>;
    public apiOtpsGenerateOtpPost(body?: UserOtpRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OtpDTO>>;
    public apiOtpsGenerateOtpPost(body?: UserOtpRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<OtpDTO>('post',`${this.basePath}/api/Otps/GenerateOtp`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiOtpsValidateOtpPost(body?: UserOtpValidateRequestDTO, observe?: 'body', reportProgress?: boolean): Observable<UserOtpValidateResultDTO>;
    public apiOtpsValidateOtpPost(body?: UserOtpValidateRequestDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserOtpValidateResultDTO>>;
    public apiOtpsValidateOtpPost(body?: UserOtpValidateRequestDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserOtpValidateResultDTO>>;
    public apiOtpsValidateOtpPost(body?: UserOtpValidateRequestDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UserOtpValidateResultDTO>('post',`${this.basePath}/api/Otps/ValidateOtp`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
