/**
 * DynastyGateway API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RemittanceDTO { 
    TimeStamp?: Date;
    RemittanceId?: string;
    TotalAmount?: number;
    RequestedAmount?: number;
    TransactionFee?: number;
    Wallet?: string;
    DateRemitted?: string;
    ReferenceNumber?: string;
    Requestee?: string;
    ApproverName?: string;
    Status?: string;
    ClientId?: number;
    MethodDescription?: string;
    CardBankName?: string;
    CardAccountName?: string;
    CardAccountNumber?: string;
    TransactionCount?: number;
    Receipts?: Array<string>;
    Files?: Array<string>;
    LettersURLs?: Array<string>;
    IDsURLs?: Array<string>;
    Remarks?: string;
    MotherCardBankName?: string;
    MotherCardAccountName?: string;
    MotherCardNickname?: string;
    MotherCardAccountNumber?: string;
    CardId?: number;
    MotherCardId?: number;
    IdNumber?: string;
    FullNameIdHolder?: string;
    IDType?: string;
}